"""
Cross-validation vector tests — Python implementation.

Runs every fixture in vectors/valid/ and vectors/invalid/ against the
Python verifier. The same fixtures are run by the TypeScript test suite,
proving byte-for-byte parity between implementations.

Vectors are generated by: python vectors/generate_vectors.py
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from algovoi_receipt_verifier import (
    ReceiptVerificationError,
    verify_compliance_receipt,
)

VECTORS = Path(__file__).parent.parent.parent / "vectors"
VALID_DIR   = VECTORS / "valid"
INVALID_DIR = VECTORS / "invalid"


def _load(d: Path) -> list[tuple[str, dict]]:
    if not d.exists():
        return []
    return [(p.name, json.loads(p.read_text(encoding="utf-8"))) for p in sorted(d.glob("*.json"))]


# ── Valid vectors ─────────────────────────────────────────────────────────────

@pytest.mark.parametrize("name,vec", _load(VALID_DIR))
def test_valid_vector(name: str, vec: dict) -> None:
    """Every valid vector must be accepted; screen_result must match declared value."""
    result = verify_compliance_receipt(
        vec["jws"],
        jwks=vec["jwks"],
        expected_payment_hash=vec.get("expected_payment_hash"),
    )
    assert result.screen_result == vec["expected_screen_result"], (
        f"{name}: expected screen_result={vec['expected_screen_result']!r}, "
        f"got {result.screen_result!r}"
    )


# ── Invalid vectors ───────────────────────────────────────────────────────────

@pytest.mark.parametrize("name,vec", _load(INVALID_DIR))
def test_invalid_vector(name: str, vec: dict) -> None:
    """Every invalid vector must be rejected with the declared error_code."""
    expected_codes = vec.get("expected_error_codes") or [vec["expected_error_code"]]

    with pytest.raises(ReceiptVerificationError) as exc_info:
        verify_compliance_receipt(
            vec["jws"],
            jwks=vec.get("jwks") or {"keys": []},
            receipt_required=vec.get("receipt_required", False),
            expected_payment_hash=vec.get("expected_payment_hash"),
        )

    assert exc_info.value.code in expected_codes, (
        f"{name}: expected error_code in {expected_codes!r}, "
        f"got {exc_info.value.code!r}: {exc_info.value.message}"
    )
